/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fciencias.concurrente.practica05;

/**
 * Clase que maneja la ventana para la cena de los filosofos
 * @author Jes&uacute;s Vila S&aacute;nchez, 309280970
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ejecucionFilosofos = new javax.swing.JFrame();
        mesa = new fciencias.concurrente.practica05.graficos.Mesa();
        numPhilosophers = new javax.swing.JTextField();
        start = new javax.swing.JToggleButton();
        stop = new javax.swing.JToggleButton();

        ejecucionFilosofos.setTitle("Cena de Filosofos");
        ejecucionFilosofos.setBackground(new java.awt.Color(0, 0, 0));
        ejecucionFilosofos.setMinimumSize(new java.awt.Dimension(400, 450));
        ejecucionFilosofos.setResizable(false);
        ejecucionFilosofos.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ejecucionFilosofosWindowClosing(evt);
            }
        });

        mesa.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout mesaLayout = new javax.swing.GroupLayout(mesa);
        mesa.setLayout(mesaLayout);
        mesaLayout.setHorizontalGroup(
            mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        mesaLayout.setVerticalGroup(
            mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ejecucionFilosofosLayout = new javax.swing.GroupLayout(ejecucionFilosofos.getContentPane());
        ejecucionFilosofos.getContentPane().setLayout(ejecucionFilosofosLayout);
        ejecucionFilosofosLayout.setHorizontalGroup(
            ejecucionFilosofosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecucionFilosofosLayout.createSequentialGroup()
                .addComponent(mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 540, Short.MAX_VALUE))
        );
        ejecucionFilosofosLayout.setVerticalGroup(
            ejecucionFilosofosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecucionFilosofosLayout.createSequentialGroup()
                .addComponent(mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 380, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cena de Filosofos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        start.setText("Iniciar");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        stop.setText("Detener");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numPhilosophers, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPhilosophers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start)
                    .addComponent(stop))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        stop.setSelected(true);
        stop.setEnabled(false);
        start.setSelected(false);
        start.setEnabled(true);
        mesa.detener();
    }//GEN-LAST:event_stopActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        start.setSelected(true);
        start.setEnabled(false);
        stop.setSelected(false);
        stop.setEnabled(true);
        String texto = numPhilosophers.getText();
        mesa.setNumFilosofos(Integer.parseInt(texto));
        mesa.iniciar();
        ejecucionFilosofos.setVisible(true);
    }//GEN-LAST:event_startActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        System.gc();
    }//GEN-LAST:event_formWindowClosing

    private void ejecucionFilosofosWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ejecucionFilosofosWindowClosing
        stop.setSelected(true);
        stop.setEnabled(false);
        start.setSelected(false);
        start.setEnabled(true);
        mesa.detener();
    }//GEN-LAST:event_ejecucionFilosofosWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ventana().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ejecucionFilosofos;
    private fciencias.concurrente.practica05.graficos.Mesa mesa;
    private javax.swing.JTextField numPhilosophers;
    private javax.swing.JToggleButton start;
    private javax.swing.JToggleButton stop;
    // End of variables declaration//GEN-END:variables

}
